services:
  quef_team.doctrine_listener.team:
    class: Quef\TeamBundle\EventListener\ORMTeamListener
    arguments: ["@event_dispatcher"]
    tags:
      - { name: doctrine.event_listener, event: postPersist, connection: default }
