parameters:
  quef_team.provider.team.default.class: Quef\TeamBundle\Security\Provider\TeamProvider
  quef_team.registry.class: Quef\TeamBundle\Metadata\Registry


services:
  quef_team.registry:
    class: %quef_team.registry.class%
    arguments: ["%quef.teams%"]

  quef_team.provider.team.default:
      class: %quef_team.provider.team.default.class%
      arguments: ["@security.token_storage"]