Quef\TeamBundle\Model\TeamInterface:
  properties:
    name:
      - NotNull:
        message:  team.name.null
        groups: [Default]
      - NotBlank:
        message:  team.name.blank
        groups: [Default]
